"""Service pages in English, French and Arabic.

Each service has one page per language (EN keeps the historical URLs). Values may contain inline HTML.
Testimonial quotes are verbatim excerpts from _build/testimonials.json.
"""

# ------------------------------------------------------------------ shared interface copy
UI = {
    "en": {
        "eyebrow": "Service", "why_h2": "Why it matters", "incl_h2": "What's included", "steps_h2": "How it works",
        "deliver_h2": "What you get", "tools_h2": "Tools I use", "proof_h2": "Results and feedback", "faq_h2": "Questions about this service",
        "others_h2": "Other services", "cta2": "See case studies", "gallery_h2": "Dashboard examples",
        "for": "For", "deliverable": "Deliverable", "languages": "Languages", "lang_value": "French and English",
        "steps": [
            ("30-minute call", "We look at your site together: your goals, what's blocking you, and the scope of the work."),
            ("Access and data", "Read access to Search Console, Analytics and, when useful, Bing Webmaster Tools. I crawl the site and gather the data."),
            ("Analysis", "I audit, measure and compare you with the competitors that matter, then turn findings into priorities."),
            ("Roadmap and walkthrough", "You get a prioritized action plan, presented live so your team knows exactly what to do and why."),
            ("Follow-up", "I can support implementation with your developers and writers, and track the results over time."),
        ],
    },
    "fr": {
        "eyebrow": "Service", "why_h2": "Pourquoi c'est important", "incl_h2": "Ce qui est inclus", "steps_h2": "Comment ça se passe",
        "deliver_h2": "Ce que vous obtenez", "tools_h2": "Les outils que j'utilise", "proof_h2": "Résultats et retours", "faq_h2": "Questions sur ce service",
        "others_h2": "Autres services", "cta2": "Voir les études de cas", "gallery_h2": "Exemples de tableaux de bord",
        "for": "Pour", "deliverable": "Livrable", "languages": "Langues", "lang_value": "Français et anglais",
        "steps": [
            ("Appel de 30 minutes", "Nous regardons votre site ensemble : vos objectifs, ce qui vous bloque et le périmètre de la mission."),
            ("Accès et données", "Un accès en lecture à la Search Console, à Analytics et, si besoin, à Bing Webmaster Tools. Je crawle le site et je collecte les données."),
            ("Analyse", "J'audite, je mesure et je vous compare aux concurrents qui comptent, puis je transforme les constats en priorités."),
            ("Roadmap et restitution", "Vous recevez un plan d'action priorisé, présenté en direct pour que votre équipe sache exactement quoi faire et pourquoi."),
            ("Suivi", "Je peux accompagner la mise en œuvre avec vos développeurs et vos rédacteurs, et suivre les résultats dans le temps."),
        ],
    },
    "ar": {
        "eyebrow": "خدمة", "why_h2": "لماذا هذا مهم", "incl_h2": "ما الذي تتضمنه الخدمة", "steps_h2": "كيف تسير العملية",
        "deliver_h2": "ما الذي تحصل عليه", "tools_h2": "الأدوات التي أستخدمها", "proof_h2": "نتائج وآراء", "faq_h2": "أسئلة حول هذه الخدمة",
        "others_h2": "خدمات أخرى", "cta2": "اطّلع على دراسات الحالة", "gallery_h2": "أمثلة على لوحات المعلومات",
        "for": "لمن", "deliverable": "المخرجات", "languages": "اللغات", "lang_value": "الفرنسية والإنجليزية",
        "steps": [
            ("مكالمة مدتها 30 دقيقة", "ننظر معًا إلى موقعك: أهدافك، وما يعيقك، ونطاق العمل."),
            ("الوصول والبيانات", "صلاحية قراءة على Search Console و Analytics، وعند الحاجة Bing Webmaster Tools. أزحف الموقع وأجمع البيانات."),
            ("التحليل", "أدقّق وأقيس وأقارنك بالمنافسين المهمّين، ثم أحوّل النتائج إلى أولويات."),
            ("خارطة الطريق والعرض", "تحصل على خطة عمل مرتبة حسب الأولوية، تُعرض مباشرة ليعرف فريقك ما يجب فعله ولماذا."),
            ("المتابعة", "يمكنني مرافقة التنفيذ مع مطوريك وكتّابك، ومتابعة النتائج مع مرور الوقت."),
        ],
    },
}

# ------------------------------------------------------------------ services
# key -> paths per language, tools, related case studies, testimonial (name, verbatim excerpt or None for the full quote), extras
SERVICES = [
    {
        "key": "seo",
        "paths": {"en": "services/seo-the-driving-force-behind-my-passion.html", "fr": "fr/services/audit-seo.html", "ar": "ar/services/seo-audit.html"},
        "tools": ["Screaming Frog", "Sitebulb", "Oncrawl", "Semrush", "Ahrefs", "Google Search Console", "Bing Webmaster Tools", "Google Analytics 4", "PageSpeed Insights", "Chrome DevTools"],
        "cases": ["ressources/seo-case-study-radco.html", "ressources/seo-case-study-interfast.html", "ressources/seo-case-study-mmt-mobile-medical-team.html"],
        "testimonial": ("Mat Gargano", None),
        "service_type": "SEO audit and consulting",
        "en": {
            "card": ("SEO audit and consulting", "Technical, semantic and competitive audits that end in a clear, prioritized roadmap."),
            "title": "SEO Consultant in Paris: SEO Audit and Strategy",
            "desc": "SEO audit and consulting by Aslane Samai, SEO consultant in Paris: technical, semantic, competitive and off-site audits, and a prioritized roadmap.",
            "h1": "SEO audit and SEO consulting",
            "lead": "A complete look at why your site isn't getting the traffic it deserves, and a prioritized plan to fix it. Technical, semantic, competitive and off-site, with the numbers to back every recommendation.",
            "for": "Companies, e-commerce sites, SaaS and agencies", "deliverable": "Audit report and prioritized roadmap",
            "why": ["Most sites lose traffic to problems nobody sees: pages Google can't crawl or chooses not to index, content that competes with itself, weak internal linking, slow templates, or authority that never reaches the pages that sell.",
                    "An audit finds these problems, measures what each one costs you, and puts them in the order that will move your numbers first. It's the starting point for everything else, including visibility in AI answers."],
            "incl": [
                ("Crawl and indexing", "How Google discovers, crawls and indexes your pages: robots.txt, sitemaps, canonicals, status codes, redirects, JavaScript rendering, crawl budget."),
                ("Site architecture and internal linking", "Depth, orphan pages, link equity and navigation, so your important pages get the attention they need."),
                ("Performance and Core Web Vitals", "LCP, INP and CLS on real templates, with fixes your developers can act on."),
                ("Semantic coverage", "Which queries you rank for, which you miss, cannibalization, and how well each page matches its search intent."),
                ("Competitive analysis", "Where the competitors that matter beat you, on content, authority and features, and where you can win."),
                ("Authority and backlinks", "Your link profile compared with competitors, toxic patterns, and a realistic netlinking plan."),
            ],
            "deliver": ["An audit report with every issue explained, measured and illustrated", "A roadmap ordered by impact and effort", "Technical specifications your developers can use directly", "Content and internal linking recommendations", "A live walkthrough with your team"],
            "faq": [
                ("What does an SEO audit include?", "Crawl and indexing, architecture and internal linking, performance and Core Web Vitals, semantic coverage, competition and backlinks. Each finding comes with its impact and a clear fix, ordered in a roadmap."),
                ("How long does an SEO audit take?", "It depends on the size and complexity of the site. We agree on the scope and the timeline during the first 30-minute call."),
                ("Do you also implement the recommendations?", "I can support implementation with your developers and writers, review changes before they go live, and track the results."),
            ],
        },
        "fr": {
            "card": ("Audit et conseil SEO", "Des audits techniques, sémantiques et concurrentiels qui débouchent sur une roadmap claire et priorisée."),
            "title": "Consultant SEO à Paris : audit SEO et stratégie",
            "desc": "Audit et conseil SEO par Aslane Samai, consultant SEO à Paris : audits technique, sémantique, concurrentiel et off-site, et roadmap priorisée.",
            "h1": "Audit SEO et conseil en référencement naturel",
            "lead": "Un diagnostic complet de ce qui empêche votre site d'obtenir le trafic qu'il mérite, et un plan priorisé pour y remédier. Technique, sémantique, concurrence et off-site, avec les chiffres derrière chaque recommandation.",
            "for": "Entreprises, e-commerce, SaaS et agences", "deliverable": "Rapport d'audit et roadmap priorisée",
            "why": ["La plupart des sites perdent du trafic à cause de problèmes invisibles : des pages que Google ne peut pas explorer ou choisit de ne pas indexer, des contenus qui se cannibalisent, un maillage interne faible, des templates lents, ou une autorité qui n'atteint jamais les pages qui vendent.",
                    "Un audit identifie ces problèmes, mesure ce que chacun vous coûte et les classe dans l'ordre qui fera bouger vos chiffres en premier. C'est le point de départ de tout le reste, y compris la visibilité dans les réponses des IA."],
            "incl": [
                ("Exploration et indexation", "Comment Google découvre, explore et indexe vos pages : robots.txt, sitemaps, canoniques, codes HTTP, redirections, rendu JavaScript, budget de crawl."),
                ("Architecture et maillage interne", "Profondeur, pages orphelines, transmission du jus et navigation, pour que vos pages importantes reçoivent l'attention qu'elles méritent."),
                ("Performance et Core Web Vitals", "LCP, INP et CLS sur vos vrais templates, avec des corrections exploitables par vos développeurs."),
                ("Couverture sémantique", "Les requêtes sur lesquelles vous êtes positionné, celles qui vous échappent, la cannibalisation et l'adéquation de chaque page à l'intention de recherche."),
                ("Analyse concurrentielle", "Là où les concurrents qui comptent vous devancent, sur le contenu, l'autorité et les fonctionnalités, et là où vous pouvez gagner."),
                ("Autorité et backlinks", "Votre profil de liens comparé à vos concurrents, les schémas à risque et un plan de netlinking réaliste."),
            ],
            "deliver": ["Un rapport d'audit où chaque problème est expliqué, mesuré et illustré", "Une roadmap classée par impact et par effort", "Des spécifications techniques directement exploitables par vos développeurs", "Des recommandations de contenu et de maillage interne", "Une restitution en direct avec votre équipe"],
            "faq": [
                ("Que comprend un audit SEO ?", "L'exploration et l'indexation, l'architecture et le maillage interne, la performance et les Core Web Vitals, la couverture sémantique, la concurrence et les backlinks. Chaque constat est accompagné de son impact et d'une correction claire, classés dans une roadmap."),
                ("Combien de temps dure un audit SEO ?", "Cela dépend de la taille et de la complexité du site. Nous fixons ensemble le périmètre et le calendrier lors du premier appel de 30 minutes."),
                ("Mettez-vous aussi en œuvre les recommandations ?", "Je peux accompagner la mise en œuvre avec vos développeurs et vos rédacteurs, relire les changements avant leur mise en ligne et suivre les résultats."),
            ],
        },
        "ar": {
            "card": ("تدقيق واستشارات SEO", "تدقيقات تقنية ودلالية وتنافسية تنتهي بخارطة طريق واضحة ومرتبة حسب الأولوية."),
            "title": "مستشار SEO في باريس: تدقيق SEO واستراتيجية",
            "desc": "تدقيق واستشارات SEO مع Aslane Samai، مستشار SEO في باريس: تدقيق تقني ودلالي وتنافسي وخارج الموقع، وخارطة طريق مرتبة حسب الأولوية.",
            "h1": "تدقيق SEO واستشارات تحسين محركات البحث",
            "lead": "فحص شامل لما يمنع موقعك من الحصول على الزيارات التي يستحقها، وخطة مرتبة حسب الأولوية لإصلاح ذلك. تقني ودلالي وتنافسي وخارج الموقع، مع الأرقام التي تدعم كل توصية.",
            "for": "الشركات، ومتاجر التجارة الإلكترونية، و SaaS، والوكالات", "deliverable": "تقرير تدقيق وخارطة طريق مرتبة حسب الأولوية",
            "why": ["تفقد معظم المواقع زياراتها بسبب مشكلات لا يراها أحد: صفحات لا يستطيع Google زحفها أو يختار عدم فهرستها، ومحتوى ينافس بعضه بعضًا، وربط داخلي ضعيف، وقوالب بطيئة، أو سلطة لا تصل أبدًا إلى الصفحات التي تبيع.",
                    "يكشف التدقيق هذه المشكلات، ويقيس كلفة كل منها، ويرتبها بحيث تتحرك أرقامك أولًا. إنه نقطة البداية لكل شيء آخر، بما في ذلك الظهور في إجابات الذكاء الاصطناعي."],
            "incl": [
                ("الزحف والفهرسة", "كيف يكتشف Google صفحاتك ويزحفها ويفهرسها: robots.txt، وخرائط الموقع، والروابط الأساسية، ورموز الحالة، وإعادة التوجيه، وعرض JavaScript، وميزانية الزحف."),
                ("بنية الموقع والربط الداخلي", "العمق، والصفحات اليتيمة، وتوزيع قوة الروابط، والتنقل، لتحظى صفحاتك المهمة بالاهتمام الذي تستحقه."),
                ("الأداء و Core Web Vitals", "LCP و INP و CLS على قوالبك الحقيقية، مع إصلاحات يستطيع مطوروك تنفيذها."),
                ("التغطية الدلالية", "الاستعلامات التي تظهر فيها، وتلك التي تفوتك، والتنافس الداخلي بين الصفحات، ومدى تطابق كل صفحة مع نية البحث."),
                ("التحليل التنافسي", "أين يتفوق عليك المنافسون المهمّون في المحتوى والسلطة والميزات، وأين يمكنك الفوز."),
                ("السلطة والروابط الخلفية", "ملف روابطك مقارنة بمنافسيك، والأنماط الخطرة، وخطة واقعية لبناء الروابط."),
            ],
            "deliver": ["تقرير تدقيق يشرح كل مشكلة ويقيسها ويوضحها", "خارطة طريق مرتبة حسب الأثر والجهد", "مواصفات تقنية يستخدمها مطوروك مباشرة", "توصيات للمحتوى والربط الداخلي", "عرض مباشر مع فريقك"],
            "faq": [
                ("ماذا يتضمن تدقيق SEO؟", "الزحف والفهرسة، والبنية والربط الداخلي، والأداء و Core Web Vitals، والتغطية الدلالية، والمنافسة، والروابط الخلفية. كل ملاحظة ترافقها قيمة أثرها وإصلاح واضح، مرتبة في خارطة طريق."),
                ("كم يستغرق تدقيق SEO؟", "يعتمد ذلك على حجم الموقع وتعقيده. نتفق على النطاق والجدول الزمني خلال المكالمة الأولى التي تستغرق 30 دقيقة."),
                ("هل تنفّذ التوصيات أيضًا؟", "يمكنني مرافقة التنفيذ مع مطوريك وكتّابك، ومراجعة التغييرات قبل نشرها، ومتابعة النتائج."),
            ],
        },
    },
    {
        "key": "geo",
        "paths": {"en": "services/geo-consulting.html", "fr": "fr/services/consultant-geo.html", "ar": "ar/services/geo.html"},
        "tools": ["Search Console generative AI report", "Bing AI Performance", "ChatGPT", "Perplexity", "Gemini", "Copilot", "Schema.org", "llms.txt", "SEO Entity Analyser", "Semantic proximity"],
        "cases": ["ressources/seo-case-study-aioseo.html"],
        "testimonial": ("Julian Cerisier", "Aslane a pris en charge des missions à forte composante GEO et SEO technique : audit technique de sites web, analyse de données de trafic et de performance, production de recommandations SEO et GEO, et restitutions client."),
        "service_type": "Generative engine optimization (GEO)",
        "en": {
            "card": ("GEO consulting", "Get your brand found, understood and cited in ChatGPT, Gemini, Perplexity and Google AI Overviews."),
            "title": "GEO Consultant: Visibility in ChatGPT and AI Overviews",
            "desc": "GEO consulting by Aslane Samai: GEO audits, LLM citation tests, entity optimization and AI-ready content to get cited in ChatGPT, Gemini and AI Overviews.",
            "h1": "GEO consulting: get cited in AI answers",
            "lead": "More and more searches end in an AI answer: Google AI Overviews and AI Mode, ChatGPT, Gemini, Perplexity, Copilot. I help your brand be found, understood and cited in those answers, with the same rigor as SEO.",
            "for": "Brands, publishers and B2B companies", "deliverable": "GEO audit, citation tests and action plan",
            "why": ["Generative engines don't show ten blue links. They pick a few sources, quote them and move on. If your content isn't crawlable by AI bots, easy to extract, backed by clear facts and consistent about who you are, someone else gets cited.",
                    "Good GEO is good SEO: the foundations are the same. GEO adds what AI systems need on top: entities, citability, structured data, and measurement of where and how often you're actually cited."],
            "incl": [
                ("AI crawler access", "Whether GPTBot, ClaudeBot, PerplexityBot, Google-Extended and the others can read your site, through robots.txt, firewalls and rendering."),
                ("LLM citation tests", "The questions your customers ask, tested across ChatGPT, Perplexity, Gemini and AI Overviews: who is cited, how often, and why."),
                ("Entities and brand consistency", "How AI systems understand your brand, products and people, and the signals that make that understanding consistent across the web."),
                ("Citable content", "Structure, facts, definitions and passages that are easy to extract and quote, without writing for robots."),
                ("Structured data and llms.txt", "Schema.org markup, an llms.txt file and clean HTML that help machines read your site correctly."),
                ("Measuring AI visibility", "Search Console's generative AI report, Bing AI Performance and citation tracking, so you can see progress."),
            ],
            "deliver": ["A GEO audit of your site and your brand", "Citation tests on your key questions, with competitors", "Technical and editorial GEO guidelines", "A prioritized action plan", "A measurement setup for AI visibility"],
            "faq": [
                ("What is GEO?", "Generative engine optimization (GEO) is the practice of making a website easy for AI systems such as ChatGPT, Gemini, Perplexity and Google AI Overviews to find, understand and cite when they generate answers."),
                ("Can you guarantee that ChatGPT will cite my site?", "No one can guarantee a citation from an AI model. What I can do is remove what prevents it, strengthen the signals that lead to citations, and measure the result."),
                ("Do I still need SEO if I do GEO?", "Yes. The pages that AI answers cite are mostly pages that already rank well. GEO builds on SEO rather than replacing it."),
            ],
        },
        "fr": {
            "card": ("Conseil GEO", "Faites trouver, comprendre et citer votre marque dans ChatGPT, Gemini, Perplexity et les Google AI Overviews."),
            "title": "Consultant GEO : visibilité dans ChatGPT et AI Overviews",
            "desc": "Consultant GEO à Paris : audits GEO, tests de citation LLM, optimisation des entités et contenus pensés pour être cités par ChatGPT, Gemini et les AI Overviews.",
            "h1": "Consultant GEO : être cité dans les réponses des IA",
            "lead": "De plus en plus de recherches se terminent par une réponse d'IA : Google AI Overviews et mode IA, ChatGPT, Gemini, Perplexity, Copilot. J'aide votre marque à être trouvée, comprise et citée dans ces réponses, avec la même rigueur que le SEO.",
            "for": "Marques, éditeurs et entreprises B2B", "deliverable": "Audit GEO, tests de citation et plan d'action",
            "why": ["Les moteurs génératifs n'affichent pas dix liens bleus. Ils choisissent quelques sources, les citent et passent à autre chose. Si votre contenu n'est pas accessible aux robots des IA, facile à extraire, appuyé sur des faits clairs et cohérent sur qui vous êtes, c'est quelqu'un d'autre qui est cité.",
                    "Good GEO is good SEO : les fondations sont les mêmes. Le GEO ajoute ce dont les IA ont besoin : entités, citabilité, données structurées, et la mesure de là où vous êtes réellement cité, et à quelle fréquence."],
            "incl": [
                ("Accès des robots IA", "GPTBot, ClaudeBot, PerplexityBot, Google-Extended et les autres peuvent-ils lire votre site ? robots.txt, pare-feu et rendu."),
                ("Tests de citation LLM", "Les questions de vos clients testées sur ChatGPT, Perplexity, Gemini et les AI Overviews : qui est cité, à quelle fréquence, et pourquoi."),
                ("Entités et cohérence de marque", "Comment les IA comprennent votre marque, vos produits et vos équipes, et les signaux qui rendent cette compréhension cohérente sur le web."),
                ("Contenus citables", "Structure, faits, définitions et passages faciles à extraire et à citer, sans écrire pour les robots."),
                ("Données structurées et llms.txt", "Balisage Schema.org, fichier llms.txt et HTML propre pour que les machines lisent correctement votre site."),
                ("Mesure de la visibilité IA", "Le rapport IA générative de la Search Console, Bing AI Performance et le suivi des citations, pour voir vos progrès."),
            ],
            "deliver": ["Un audit GEO de votre site et de votre marque", "Des tests de citation sur vos questions clés, avec vos concurrents", "Des guidelines GEO techniques et éditoriales", "Un plan d'action priorisé", "Un dispositif de mesure de la visibilité IA"],
            "faq": [
                ("Qu'est-ce que le GEO ?", "Le GEO (generative engine optimization) consiste à rendre un site facile à trouver, à comprendre et à citer pour les IA comme ChatGPT, Gemini, Perplexity et les Google AI Overviews lorsqu'elles génèrent leurs réponses."),
                ("Pouvez-vous garantir que ChatGPT citera mon site ?", "Personne ne peut garantir une citation par un modèle d'IA. Ce que je peux faire : lever ce qui l'empêche, renforcer les signaux qui mènent aux citations, et mesurer le résultat."),
                ("Ai-je encore besoin de SEO si je fais du GEO ?", "Oui. Les pages citées par les réponses des IA sont surtout des pages déjà bien positionnées. Le GEO s'appuie sur le SEO, il ne le remplace pas."),
            ],
        },
        "ar": {
            "card": ("استشارات GEO", "اجعل علامتك التجارية تُكتشف وتُفهم ويُستشهد بها في ChatGPT و Gemini و Perplexity و Google AI Overviews."),
            "title": "مستشار GEO: الظهور في ChatGPT و AI Overviews",
            "desc": "استشارات GEO مع Aslane Samai: تدقيق GEO، واختبارات استشهاد LLM، وتحسين الكيانات، ومحتوى جاهز ليستشهد به ChatGPT و Gemini و AI Overviews.",
            "h1": "استشارات GEO: أن يُستشهد بك في إجابات الذكاء الاصطناعي",
            "lead": "ينتهي عدد متزايد من عمليات البحث بإجابة من الذكاء الاصطناعي: Google AI Overviews و AI Mode، و ChatGPT، و Gemini، و Perplexity، و Copilot. أساعد علامتك التجارية على أن تُكتشف وتُفهم ويُستشهد بها في هذه الإجابات، بدقة SEO نفسها.",
            "for": "العلامات التجارية، والناشرون، وشركات B2B", "deliverable": "تدقيق GEO، واختبارات استشهاد، وخطة عمل",
            "why": ["لا تعرض المحركات التوليدية عشرة روابط زرقاء. إنها تختار بضعة مصادر، وتستشهد بها، ثم تمضي. إذا لم يكن محتواك قابلًا للقراءة من زواحف الذكاء الاصطناعي، وسهل الاستخراج، ومدعومًا بحقائق واضحة، ومتسقًا في تعريف هويتك، فسيُستشهد بغيرك.",
                    "Good GEO is good SEO: الأسس واحدة. يضيف GEO ما تحتاجه أنظمة الذكاء الاصطناعي: الكيانات، وقابلية الاستشهاد، والبيانات المنظمة، وقياس أين ومتى يُستشهد بك فعلًا."],
            "incl": [
                ("وصول زواحف الذكاء الاصطناعي", "هل تستطيع GPTBot و ClaudeBot و PerplexityBot و Google-Extended وغيرها قراءة موقعك؟ عبر robots.txt والجدران النارية وطريقة العرض."),
                ("اختبارات استشهاد LLM", "أسئلة عملائك مختبرة على ChatGPT و Perplexity و Gemini و AI Overviews: من يُستشهد به، وكم مرة، ولماذا."),
                ("الكيانات واتساق العلامة التجارية", "كيف تفهم أنظمة الذكاء الاصطناعي علامتك ومنتجاتك وفريقك، والإشارات التي تجعل هذا الفهم متسقًا على الويب."),
                ("محتوى قابل للاستشهاد", "بنية، وحقائق، وتعريفات، وفقرات يسهل استخراجها واقتباسها، دون الكتابة للروبوتات."),
                ("البيانات المنظمة و llms.txt", "ترميز Schema.org، وملف llms.txt، و HTML نظيف لتقرأ الآلات موقعك بشكل صحيح."),
                ("قياس الظهور في الذكاء الاصطناعي", "تقرير الذكاء الاصطناعي التوليدي في Search Console، و Bing AI Performance، وتتبع الاستشهادات، لترى تقدمك."),
            ],
            "deliver": ["تدقيق GEO لموقعك وعلامتك التجارية", "اختبارات استشهاد على أسئلتك الرئيسية، مع المنافسين", "إرشادات GEO تقنية وتحريرية", "خطة عمل مرتبة حسب الأولوية", "منظومة لقياس الظهور في الذكاء الاصطناعي"],
            "faq": [
                ("ما هو GEO؟", "تحسين المحركات التوليدية (GEO) هو جعل الموقع سهل العثور عليه وفهمه والاستشهاد به من قِبل أنظمة الذكاء الاصطناعي مثل ChatGPT و Gemini و Perplexity و Google AI Overviews عند توليد إجاباتها."),
                ("هل يمكنك ضمان أن يستشهد ChatGPT بموقعي؟", "لا يمكن لأحد ضمان استشهاد نموذج ذكاء اصطناعي. ما يمكنني فعله هو إزالة ما يمنع ذلك، وتقوية الإشارات التي تؤدي إلى الاستشهاد، وقياس النتيجة."),
                ("هل ما زلت بحاجة إلى SEO إذا عملت على GEO؟", "نعم. الصفحات التي تستشهد بها إجابات الذكاء الاصطناعي هي غالبًا صفحات تتصدر النتائج أصلًا. يبني GEO على SEO ولا يحل محله."),
            ],
        },
    },
    {
        "key": "content",
        "paths": {"en": "services/seo-content-writing.html", "fr": "fr/services/redaction-seo.html", "ar": "ar/services/seo-content.html"},
        "tools": ["Semrush", "Ahrefs", "Google Search Console", "KeyBERT", "sentence-transformers", "WordPress"],
        "cases": ["ressources/seo-case-study-mmt-mobile-medical-team.html", "ressources/seo-case-study-unimind.html", "ressources/seo-case-study-aioseo.html"],
        "testimonial": ("Vincent Leutwiler", None),
        "service_type": "SEO content writing",
        "en": {
            "card": ("SEO and GEO content", "Keyword research, briefs and articles in French and English that rank and get cited."),
            "title": "SEO Content Writing and Briefs in English and French",
            "desc": "SEO and GEO content by Aslane Samai: keyword research, semantic clustering, content briefs and articles in English and French that rank and get cited by AI.",
            "h1": "SEO and GEO content writing",
            "lead": "Content built from what people actually search for: keyword research, semantic clustering, detailed briefs and articles in French and English, written to rank on Google and to be quoted by AI answers.",
            "for": "Companies, publishers and content teams", "deliverable": "Content strategy, briefs and articles",
            "why": ["Publishing more doesn't mean ranking more. Content works when it targets a real search intent, covers the topic better than what already ranks, and fits into a clear structure of pages that support each other.",
                    "The same qualities make content easy for AI systems to quote: clear answers, precise facts and a structure that's easy to extract."],
            "incl": [
                ("Keyword research", "The queries your audience uses, their volume, their intent and the competition behind them."),
                ("Semantic clustering", "Topics grouped into clusters and pillar pages, so each page has one clear job and pages don't compete."),
                ("Content briefs", "For your writers: intent, structure, questions to answer, entities to cover, internal links and sources."),
                ("Writing in French and English", "Articles and landing pages written for readers first, with search and AI answers in mind."),
                ("Optimization of existing content", "Updating and improving pages that are close to ranking, often the fastest wins."),
                ("GEO-ready formatting", "Definitions, facts, tables and concise answers that AI systems can extract and cite."),
            ],
            "deliver": ["A keyword and topic map", "An editorial plan in priority order", "Detailed briefs, ready for your writers", "Articles and landing pages in French or English", "Editorial follow-up and performance tracking"],
            "faq": [
                ("Do you write in French and English?", "Yes. I write and produce briefs in both languages."),
                ("Can you work with our existing writers?", "Yes. I can write the briefs and review the content your team produces, so your writers focus on what they do best."),
                ("How is SEO content different from GEO content?", "The foundations are the same. GEO-ready content adds clear definitions, precise facts and passages that AI systems can extract and quote easily."),
            ],
        },
        "fr": {
            "card": ("Contenus SEO et GEO", "Recherche de mots-clés, briefs et articles en français et en anglais qui se positionnent et sont cités."),
            "title": "Rédaction SEO et briefs de contenu en français et en anglais",
            "desc": "Contenus SEO et GEO par Aslane Samai : recherche de mots-clés, clustering sémantique, briefs et articles en français et en anglais qui se positionnent et sont cités.",
            "h1": "Rédaction de contenus SEO et GEO",
            "lead": "Des contenus construits à partir de ce que les gens recherchent vraiment : recherche de mots-clés, clustering sémantique, briefs détaillés et articles en français et en anglais, écrits pour se positionner sur Google et être cités par les IA.",
            "for": "Entreprises, éditeurs et équipes de contenu", "deliverable": "Stratégie de contenu, briefs et articles",
            "why": ["Publier plus ne veut pas dire se positionner plus. Un contenu fonctionne quand il vise une vraie intention de recherche, couvre le sujet mieux que ce qui est déjà positionné, et s'inscrit dans une structure claire de pages qui se renforcent.",
                    "Ces mêmes qualités rendent un contenu facile à citer pour les IA : des réponses claires, des faits précis et une structure facile à extraire."],
            "incl": [
                ("Recherche de mots-clés", "Les requêtes de votre audience, leur volume, leur intention et la concurrence derrière."),
                ("Clustering sémantique", "Les sujets regroupés en clusters et pages piliers, pour que chaque page ait un rôle clair et que les pages ne se concurrencent pas."),
                ("Briefs de contenu", "Pour vos rédacteurs : intention, structure, questions à traiter, entités à couvrir, liens internes et sources."),
                ("Rédaction en français et en anglais", "Articles et landing pages écrits d'abord pour les lecteurs, en pensant à la recherche et aux réponses des IA."),
                ("Optimisation des contenus existants", "Mettre à jour et améliorer les pages proches du top 10, souvent les gains les plus rapides."),
                ("Mise en forme pensée pour le GEO", "Définitions, faits, tableaux et réponses concises que les IA peuvent extraire et citer."),
            ],
            "deliver": ["Une cartographie des mots-clés et des sujets", "Un plan éditorial priorisé", "Des briefs détaillés, prêts pour vos rédacteurs", "Des articles et landing pages en français ou en anglais", "Un suivi éditorial et des performances"],
            "faq": [
                ("Rédigez-vous en français et en anglais ?", "Oui. Je rédige et je produis des briefs dans les deux langues."),
                ("Pouvez-vous travailler avec nos rédacteurs ?", "Oui. Je peux rédiger les briefs et relire les contenus produits par votre équipe, pour que vos rédacteurs se concentrent sur ce qu'ils font de mieux."),
                ("Quelle différence entre un contenu SEO et un contenu GEO ?", "Les fondations sont les mêmes. Un contenu pensé pour le GEO ajoute des définitions claires, des faits précis et des passages que les IA peuvent facilement extraire et citer."),
            ],
        },
        "ar": {
            "card": ("محتوى SEO و GEO", "بحث عن الكلمات المفتاحية، وموجزات، ومقالات بالفرنسية والإنجليزية تتصدر النتائج ويُستشهد بها."),
            "title": "كتابة محتوى SEO وموجزات بالفرنسية والإنجليزية",
            "desc": "محتوى SEO و GEO مع Aslane Samai: بحث عن الكلمات المفتاحية، وتجميع دلالي، وموجزات ومقالات بالفرنسية والإنجليزية تتصدر النتائج ويستشهد بها الذكاء الاصطناعي.",
            "h1": "كتابة محتوى SEO و GEO",
            "lead": "محتوى مبني على ما يبحث عنه الناس فعلًا: بحث عن الكلمات المفتاحية، وتجميع دلالي، وموجزات مفصلة، ومقالات بالفرنسية والإنجليزية، مكتوبة لتتصدر Google ولتقتبسها إجابات الذكاء الاصطناعي.",
            "for": "الشركات، والناشرون، وفرق المحتوى", "deliverable": "استراتيجية محتوى، وموجزات، ومقالات",
            "why": ["النشر أكثر لا يعني الظهور أكثر. ينجح المحتوى عندما يستهدف نية بحث حقيقية، ويغطي الموضوع أفضل مما يتصدر حاليًا، ويندرج في بنية واضحة من صفحات يدعم بعضها بعضًا.",
                    "الصفات نفسها تجعل المحتوى سهل الاقتباس لأنظمة الذكاء الاصطناعي: إجابات واضحة، وحقائق دقيقة، وبنية يسهل استخراجها."],
            "incl": [
                ("البحث عن الكلمات المفتاحية", "الاستعلامات التي يستخدمها جمهورك، وحجمها، ونيتها، والمنافسة عليها."),
                ("التجميع الدلالي", "مواضيع مجمعة في مجموعات وصفحات محورية، لتكون لكل صفحة مهمة واضحة ولا تتنافس الصفحات فيما بينها."),
                ("موجزات المحتوى", "لكتّابك: النية، والبنية، والأسئلة المطلوب الإجابة عنها، والكيانات، والروابط الداخلية، والمصادر."),
                ("الكتابة بالفرنسية والإنجليزية", "مقالات وصفحات هبوط مكتوبة للقراء أولًا، مع مراعاة البحث وإجابات الذكاء الاصطناعي."),
                ("تحسين المحتوى الحالي", "تحديث وتحسين الصفحات القريبة من المراتب الأولى، وهي غالبًا أسرع المكاسب."),
                ("تنسيق جاهز لـ GEO", "تعريفات، وحقائق، وجداول، وإجابات موجزة يمكن لأنظمة الذكاء الاصطناعي استخراجها والاستشهاد بها."),
            ],
            "deliver": ["خريطة للكلمات المفتاحية والمواضيع", "خطة تحريرية مرتبة حسب الأولوية", "موجزات مفصلة جاهزة لكتّابك", "مقالات وصفحات هبوط بالفرنسية أو الإنجليزية", "متابعة تحريرية وتتبع للأداء"],
            "faq": [
                ("هل تكتب بالفرنسية والإنجليزية؟", "نعم. أكتب المحتوى وأعد الموجزات باللغتين."),
                ("هل يمكنك العمل مع كتّابنا الحاليين؟", "نعم. يمكنني إعداد الموجزات ومراجعة المحتوى الذي ينتجه فريقك، ليركز كتّابك على ما يجيدونه."),
                ("ما الفرق بين محتوى SEO ومحتوى GEO؟", "الأسس واحدة. يضيف المحتوى الجاهز لـ GEO تعريفات واضحة، وحقائق دقيقة، وفقرات يسهل على أنظمة الذكاء الاصطناعي استخراجها واقتباسها."),
            ],
        },
    },
    {
        "key": "data",
        "paths": {"en": "services/data-analysis.html", "fr": "fr/services/analyse-donnees-seo.html", "ar": "ar/services/seo-data-analysis.html"},
        "tools": ["Python (pandas)", "SQL (BigQuery)", "Search Console API", "Ahrefs API", "sentence-transformers", "TimesFM", "Prophet"],
        "cases": ["ressources/seo-case-study-aioseo.html", "ressources/seo-case-study-radco.html"],
        "testimonial": ("Hedi Marinier", None),
        "service_type": "SEO data analysis",
        "en": {
            "card": ("SEO data analysis", "Python, SQL and BigQuery to find where traffic is won or lost, and forecast what comes next."),
            "title": "SEO Data Analysis with Python, SQL and BigQuery",
            "desc": "SEO data analysis by Aslane Samai: Search Console and analytics data in Python, SQL and BigQuery to find where traffic is won or lost, plus traffic forecasts.",
            "h1": "SEO data analysis with Python and SQL",
            "lead": "Search Console only shows you part of the picture. I pull your search, analytics and crawl data together with Python, SQL and BigQuery to find where traffic is won or lost, and which fixes will actually move the numbers.",
            "for": "Sites with a lot of pages, queries or markets", "deliverable": "Analyses, forecasts and recommendations",
            "why": ["On large sites, intuition doesn't scale. Traffic drops hide in page groups, markets or query types, and the interface of the tools can't show them. Data analysis turns thousands of rows into a few clear decisions.",
                    "It also answers the questions that matter to the business: what an update really cost, which sections deserve investment, and what traffic to expect next quarter."],
            "incl": [
                ("Search Console at scale", "Full exports through the API, beyond the 1,000-row limit of the interface, by page, query, country and device."),
                ("Drops and anomalies", "What changed, where and when: updates, migrations, cannibalization, seasonality or tracking issues."),
                ("Segmentation", "Traffic by template, section, topic cluster, market or intent, to see what really drives results."),
                ("Semantic proximity", "Embeddings to measure how well each page matches the queries it should rank for, compared with competitors."),
                ("Traffic forecasting", "Forecasts of clicks, impressions and positions with Google's TimesFM and Meta's Prophet."),
                ("Automation", "Recurring analyses automated in Python and SQL, so you get the same answers every month without the manual work."),
            ],
            "deliver": ["Clear answers to your business questions", "Segmented analyses of your search data", "Traffic forecasts with their assumptions", "Reusable Python notebooks or SQL queries", "Recommendations ordered by impact"],
            "faq": [
                ("What data do you need?", "Read access to Search Console, and ideally to Google Analytics 4 or BigQuery exports. I can also work from CSV exports."),
                ("Why not just use the Search Console interface?", "The interface samples and limits the data. The API and BigQuery give access to much more detail, which you can segment and combine with other sources."),
                ("Can you forecast our organic traffic?", "Yes, with models such as TimesFM and Prophet, based on your history. Forecasts come with their assumptions and limits."),
            ],
        },
        "fr": {
            "card": ("Analyse de données SEO", "Python, SQL et BigQuery pour trouver où le trafic se gagne ou se perd, et prévoir la suite."),
            "title": "Analyse de données SEO avec Python, SQL et BigQuery",
            "desc": "Analyse de données SEO avec Python, SQL et BigQuery : trouver où le trafic se gagne ou se perd dans vos données Search Console, et prévoir la suite.",
            "h1": "Analyse de données SEO avec Python et SQL",
            "lead": "La Search Console ne montre qu'une partie de la réalité. Je croise vos données de recherche, d'analytics et de crawl avec Python, SQL et BigQuery pour trouver où le trafic se gagne ou se perd, et quelles corrections feront vraiment bouger les chiffres.",
            "for": "Sites avec beaucoup de pages, de requêtes ou de marchés", "deliverable": "Analyses, prévisions et recommandations",
            "why": ["Sur les gros sites, l'intuition ne suffit plus. Les baisses de trafic se cachent dans des groupes de pages, des marchés ou des types de requêtes que l'interface des outils ne montre pas. L'analyse de données transforme des milliers de lignes en quelques décisions claires.",
                    "Elle répond aussi aux questions qui comptent pour l'entreprise : ce qu'une mise à jour a vraiment coûté, quelles sections méritent l'investissement, et quel trafic attendre au prochain trimestre."],
            "incl": [
                ("La Search Console à grande échelle", "Des exports complets via l'API, au-delà de la limite de 1 000 lignes de l'interface, par page, requête, pays et appareil."),
                ("Baisses et anomalies", "Ce qui a changé, où et quand : mises à jour, migrations, cannibalisation, saisonnalité ou problèmes de tracking."),
                ("Segmentation", "Le trafic par template, section, cluster thématique, marché ou intention, pour voir ce qui porte vraiment les résultats."),
                ("Proximité sémantique", "Des embeddings pour mesurer l'adéquation de chaque page aux requêtes qu'elle devrait cibler, face aux concurrents."),
                ("Prévision du trafic", "Des prévisions de clics, d'impressions et de positions avec TimesFM de Google et Prophet de Meta."),
                ("Automatisation", "Les analyses récurrentes automatisées en Python et SQL, pour obtenir les mêmes réponses chaque mois sans travail manuel."),
            ],
            "deliver": ["Des réponses claires à vos questions business", "Des analyses segmentées de vos données de recherche", "Des prévisions de trafic avec leurs hypothèses", "Des notebooks Python ou requêtes SQL réutilisables", "Des recommandations classées par impact"],
            "faq": [
                ("De quelles données avez-vous besoin ?", "Un accès en lecture à la Search Console, et idéalement à Google Analytics 4 ou aux exports BigQuery. Je peux aussi travailler à partir d'exports CSV."),
                ("Pourquoi ne pas simplement utiliser l'interface de la Search Console ?", "L'interface échantillonne et limite les données. L'API et BigQuery donnent accès à beaucoup plus de détail, qu'on peut segmenter et croiser avec d'autres sources."),
                ("Pouvez-vous prévoir notre trafic organique ?", "Oui, avec des modèles comme TimesFM et Prophet, à partir de votre historique. Les prévisions sont accompagnées de leurs hypothèses et de leurs limites."),
            ],
        },
        "ar": {
            "card": ("تحليل بيانات SEO", "Python و SQL و BigQuery لمعرفة أين تُكسب الزيارات وأين تُفقد، وتوقّع ما سيأتي."),
            "title": "تحليل بيانات SEO باستخدام Python و SQL و BigQuery",
            "desc": "تحليل بيانات SEO مع Aslane Samai: بيانات Search Console والتحليلات عبر Python و SQL و BigQuery لمعرفة أين تُكسب الزيارات وأين تُفقد، مع توقعات الزيارات.",
            "h1": "تحليل بيانات SEO باستخدام Python و SQL",
            "lead": "لا تُظهر Search Console إلا جزءًا من الصورة. أجمع بيانات البحث والتحليلات والزحف باستخدام Python و SQL و BigQuery لمعرفة أين تُكسب الزيارات وأين تُفقد، وأي الإصلاحات ستحرّك الأرقام فعلًا.",
            "for": "المواقع ذات الصفحات أو الاستعلامات أو الأسواق الكثيرة", "deliverable": "تحليلات، وتوقعات، وتوصيات",
            "why": ["في المواقع الكبيرة، لا يكفي الحدس. تختبئ انخفاضات الزيارات في مجموعات صفحات أو أسواق أو أنواع استعلامات لا تُظهرها واجهات الأدوات. يحوّل تحليل البيانات آلاف الصفوف إلى بضعة قرارات واضحة.",
                    "ويجيب أيضًا عن الأسئلة المهمة للشركة: ما الكلفة الحقيقية لتحديث ما، وأي الأقسام تستحق الاستثمار، وما الزيارات المتوقعة في الربع القادم."],
            "incl": [
                ("Search Console على نطاق واسع", "تصدير كامل عبر الواجهة البرمجية، أبعد من حد 1,000 صف في الواجهة، حسب الصفحة والاستعلام والبلد والجهاز."),
                ("الانخفاضات والحالات الشاذة", "ما الذي تغيّر، وأين، ومتى: تحديثات، أو عمليات نقل، أو تنافس داخلي، أو موسمية، أو مشكلات في التتبع."),
                ("التقسيم", "الزيارات حسب القالب أو القسم أو المجموعة الموضوعية أو السوق أو النية، لمعرفة ما يصنع النتائج فعلًا."),
                ("القرب الدلالي", "تضمينات (embeddings) لقياس مدى تطابق كل صفحة مع الاستعلامات التي يجب أن تظهر فيها، مقارنة بالمنافسين."),
                ("توقّع الزيارات", "توقعات للنقرات ومرات الظهور والترتيب باستخدام TimesFM من Google و Prophet من Meta."),
                ("الأتمتة", "تحليلات متكررة مؤتمتة بـ Python و SQL، لتحصل على الإجابات نفسها كل شهر دون عمل يدوي."),
            ],
            "deliver": ["إجابات واضحة عن أسئلتك التجارية", "تحليلات مقسمة لبيانات البحث لديك", "توقعات للزيارات مع افتراضاتها", "دفاتر Python أو استعلامات SQL قابلة لإعادة الاستخدام", "توصيات مرتبة حسب الأثر"],
            "faq": [
                ("ما البيانات التي تحتاجها؟", "صلاحية قراءة على Search Console، ويفضَّل على Google Analytics 4 أو تصديرات BigQuery. يمكنني أيضًا العمل من ملفات CSV."),
                ("لماذا لا نكتفي بواجهة Search Console؟", "تأخذ الواجهة عينات من البيانات وتحدّها. أما الواجهة البرمجية و BigQuery فتتيحان تفاصيل أكثر بكثير، يمكن تقسيمها ودمجها مع مصادر أخرى."),
                ("هل يمكنك توقّع زياراتنا العضوية؟", "نعم، بنماذج مثل TimesFM و Prophet انطلاقًا من بياناتك التاريخية. تأتي التوقعات مع افتراضاتها وحدودها."),
            ],
        },
    },
    {
        "key": "viz",
        "paths": {"en": "services/data-visualization.html", "fr": "fr/services/dashboards-seo.html", "ar": "ar/services/seo-dashboards.html"},
        "tools": ["Looker Studio", "Tableau", "Google Analytics 4", "Google Search Console", "BigQuery"],
        "cases": ["ressources/seo-case-study-aioseo.html"],
        "testimonial": ("Nazim Zidi", "il a une grande expérience en matière d'analyse de données et peut facilement interpréter les chiffres pour aider à prendre des décisions stratégiques."),
        "service_type": "SEO dashboards and data visualization",
        "gallery": [
            ("https://misinate.sirv.com/perso/linkedin.webp", {"en": "LinkedIn profile data", "fr": "Données de profil LinkedIn", "ar": "بيانات ملف LinkedIn"}),
            ("https://misinate.sirv.com/perso/netflix.webp", {"en": "Netflix around the world", "fr": "Netflix dans le monde", "ar": "Netflix حول العالم"}),
            ("https://misinate.sirv.com/perso/wallmart.webp", {"en": "Walmart across the US", "fr": "Walmart aux États-Unis", "ar": "Walmart في الولايات المتحدة"}),
            ("https://misinate.sirv.com/perso/covid-deaths.webp", {"en": "Covid deaths per country", "fr": "Décès liés au Covid par pays", "ar": "وفيات Covid حسب البلد"}),
        ],
        "en": {
            "card": ("SEO dashboards", "Looker Studio and Tableau dashboards that turn search data into decisions your team can follow."),
            "title": "SEO Dashboards and Data Visualization (Looker Studio, Tableau)",
            "desc": "SEO dashboards by Aslane Samai: Looker Studio and Tableau reports that combine Search Console, GA4 and SEA data into clear, shareable decisions.",
            "h1": "SEO dashboards and data visualization",
            "lead": "Reports people actually read. I build Looker Studio and Tableau dashboards that bring Search Console, Google Analytics 4, SEA and business data together, and answer your team's questions at a glance.",
            "for": "Marketing teams, managers and clients", "deliverable": "Dashboards and a reporting routine",
            "why": ["Most SEO reports are screenshots of tools: lots of numbers, few answers. A good dashboard starts from the decisions you need to make, shows the few metrics that matter, and updates itself.",
                    "It also makes SEO visible to the rest of the company, which is often what unlocks budget and developer time."],
            "incl": [
                ("KPI definition", "The metrics that match your goals, and the questions each dashboard page must answer."),
                ("Data connections", "Search Console, GA4, BigQuery, SEA and CRM or sales data where it helps."),
                ("SEO and SEA in one view", "Consolidated organic and paid search reporting, so channels are read together."),
                ("Segmentation", "By section, template, market, device or brand versus non-brand queries."),
                ("Automated refresh", "Dashboards that update on their own, with no weekly copy and paste."),
                ("Handover and training", "Your team learns to read, filter and extend the dashboards."),
            ],
            "deliver": ["Looker Studio or Tableau dashboards", "A clear definition of each KPI", "Automated data connections", "Documentation and a training session", "A reporting routine (monthly or weekly)"],
            "faq": [
                ("Looker Studio or Tableau?", "Looker Studio is free and connects natively to Google tools, which suits most SEO reporting. Tableau is useful when you already use it or need heavier analysis."),
                ("Can the dashboards include paid search and sales data?", "Yes. I've built consolidated SEO and SEA reports, and data from your CRM or sales tools can be added when it helps answer your questions."),
                ("Who can access the dashboards?", "You own them. They can be shared with your team, managers or clients with the access rights you choose."),
            ],
        },
        "fr": {
            "card": ("Dashboards SEO", "Des tableaux de bord Looker Studio et Tableau qui transforment les données de recherche en décisions."),
            "title": "Dashboards SEO et data visualisation (Looker Studio, Tableau)",
            "desc": "Dashboards SEO par Aslane Samai : rapports Looker Studio et Tableau qui réunissent Search Console, GA4 et SEA en décisions claires et partageables.",
            "h1": "Dashboards SEO et data visualisation",
            "lead": "Des rapports que les gens lisent vraiment. Je construis des tableaux de bord Looker Studio et Tableau qui réunissent Search Console, Google Analytics 4, SEA et données business, et répondent en un coup d'œil aux questions de votre équipe.",
            "for": "Équipes marketing, managers et clients", "deliverable": "Tableaux de bord et routine de reporting",
            "why": ["La plupart des reportings SEO sont des captures d'écran d'outils : beaucoup de chiffres, peu de réponses. Un bon dashboard part des décisions à prendre, montre les quelques indicateurs qui comptent, et se met à jour tout seul.",
                    "Il rend aussi le SEO visible pour le reste de l'entreprise, ce qui débloque souvent du budget et du temps de développement."],
            "incl": [
                ("Définition des KPI", "Les indicateurs alignés sur vos objectifs, et les questions auxquelles chaque page du dashboard doit répondre."),
                ("Connexion des données", "Search Console, GA4, BigQuery, SEA, et données CRM ou ventes quand elles sont utiles."),
                ("SEO et SEA dans une même vue", "Un reporting consolidé du référencement naturel et payant, pour lire les canaux ensemble."),
                ("Segmentation", "Par section, template, marché, appareil ou requêtes de marque et hors marque."),
                ("Actualisation automatique", "Des dashboards qui se mettent à jour seuls, sans copier-coller chaque semaine."),
                ("Passation et formation", "Votre équipe apprend à lire, filtrer et faire évoluer les dashboards."),
            ],
            "deliver": ["Des tableaux de bord Looker Studio ou Tableau", "Une définition claire de chaque KPI", "Des connexions de données automatisées", "Une documentation et une session de formation", "Une routine de reporting (mensuelle ou hebdomadaire)"],
            "faq": [
                ("Looker Studio ou Tableau ?", "Looker Studio est gratuit et se connecte nativement aux outils Google, ce qui convient à la plupart des reportings SEO. Tableau est utile si vous l'utilisez déjà ou pour des analyses plus lourdes."),
                ("Les dashboards peuvent-ils inclure le SEA et les ventes ?", "Oui. J'ai construit des rapports consolidés SEO et SEA, et les données de votre CRM ou de vos outils de vente peuvent être ajoutées quand elles aident à répondre à vos questions."),
                ("Qui a accès aux dashboards ?", "Ils vous appartiennent. Ils peuvent être partagés avec votre équipe, vos managers ou vos clients, avec les droits d'accès que vous choisissez."),
            ],
        },
        "ar": {
            "card": ("لوحات معلومات SEO", "لوحات Looker Studio و Tableau تحوّل بيانات البحث إلى قرارات يفهمها فريقك."),
            "title": "لوحات معلومات SEO وتصوير البيانات (Looker Studio و Tableau)",
            "desc": "لوحات معلومات SEO مع Aslane Samai: تقارير Looker Studio و Tableau تجمع Search Console و GA4 و SEA في قرارات واضحة وقابلة للمشاركة.",
            "h1": "لوحات معلومات SEO وتصوير البيانات",
            "lead": "تقارير يقرؤها الناس فعلًا. أبني لوحات معلومات على Looker Studio و Tableau تجمع Search Console و Google Analytics 4 و SEA وبيانات الأعمال، وتجيب عن أسئلة فريقك بنظرة واحدة.",
            "for": "فرق التسويق، والمدراء، والعملاء", "deliverable": "لوحات معلومات وروتين للتقارير",
            "why": ["معظم تقارير SEO لقطات شاشة من الأدوات: أرقام كثيرة وإجابات قليلة. تنطلق لوحة المعلومات الجيدة من القرارات المطلوب اتخاذها، وتعرض المؤشرات القليلة المهمة، وتتحدث تلقائيًا.",
                    "كما تجعل SEO مرئيًا لبقية الشركة، وهو غالبًا ما يفتح الميزانية ووقت المطورين."],
            "incl": [
                ("تحديد مؤشرات الأداء", "المؤشرات المتوافقة مع أهدافك، والأسئلة التي يجب أن تجيب عنها كل صفحة من اللوحة."),
                ("ربط البيانات", "Search Console و GA4 و BigQuery و SEA، وبيانات CRM أو المبيعات عند الحاجة."),
                ("SEO و SEA في عرض واحد", "تقارير موحدة للبحث العضوي والمدفوع، لقراءة القنوات معًا."),
                ("التقسيم", "حسب القسم أو القالب أو السوق أو الجهاز، أو استعلامات العلامة التجارية مقابل غيرها."),
                ("تحديث تلقائي", "لوحات تتحدث من تلقاء نفسها، دون نسخ ولصق كل أسبوع."),
                ("التسليم والتدريب", "يتعلم فريقك قراءة اللوحات وتصفيتها وتطويرها."),
            ],
            "deliver": ["لوحات معلومات على Looker Studio أو Tableau", "تعريف واضح لكل مؤشر", "روابط بيانات مؤتمتة", "توثيق وجلسة تدريب", "روتين للتقارير (شهري أو أسبوعي)"],
            "faq": [
                ("Looker Studio أم Tableau؟", "Looker Studio مجاني ويتصل مباشرة بأدوات Google، وهو مناسب لمعظم تقارير SEO. أما Tableau فمفيد إذا كنت تستخدمه أصلًا أو تحتاج إلى تحليلات أثقل."),
                ("هل يمكن أن تشمل اللوحات بيانات SEA والمبيعات؟", "نعم. بنيت تقارير موحدة لـ SEO و SEA، ويمكن إضافة بيانات CRM أو أدوات المبيعات عندما تساعد في الإجابة عن أسئلتك."),
                ("من يمكنه الوصول إلى اللوحات؟", "إنها ملكك. يمكن مشاركتها مع فريقك أو مدرائك أو عملائك بصلاحيات الوصول التي تختارها."),
            ],
        },
    },
]
